### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by doamatto** [risinqcki/Incondite-Media-Center#1]
Hello!

I am making a fork of Incondite Media Center (shortened down to "Incondite," so not much of a change). However, I did not see any licensing information. I would like to ask if there is a specific license I should use to license the code of my fork or if I can use (virtually) whatever. I, personally, would like to use a GPL-v3, however, I would like the decision to be up to the original developers. Regardless, I have made attributions in the README and (to be added into new features) of the Incondite app.

Thanks for your help in advance!

P.S. The fork is being made [here](https://github.com/KnoxDevTeam/Incondite-Media-Center)

**Comment by risinqcki** [comment]
Hello,
Feel free to use whatever license you desire for the code. If you wish to proceed with a GPL variant let me know and I will update this project to the same license to protect the foundations your project.

As for any images, I am unaware of there origins at this point. To be safe I will be replacing them with images from the public domain.

I am glad to see someone building upon this project.
Thanks.

**Comment by risinqcki** [comment]
Hello,
I noticed there was some sensitive information in past commits.
Can you delete the fork and create a new one from this version?

Thanks

**Comment by doamatto** [comment]
Howdy,

I'm completely fine with re-forking. Give me about 10-15 minutes and it'll be updated properly

**Comment by doamatto** [comment]
Also, yes: I plan to use a GPL v3 license

**Comment by doamatto** [comment]
@risinqcki I have just finished re-forking the repo and added the LICENSE file for GPL-v3. You can close this whenever you feel like as of this time.

**Comment by risinqcki** [comment]
Thanks,
If you have any questions let me know.
I don't have a lot of time to work on side projects anymore but I will try to answer any questions.
